added user icon
AndreiToader1/connatix-internship pull request #3
Opened 2022-04-12 07:19 UTC by ralucaaianos

2022-04-15 13:34 UTC, Lazar-Adrian requested changes

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        return this.getHeader().locator('div.user-icon');
Remove dependency of other elements in page, and add a unique locator for this specific element

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    async waitForUserIcon(): Promise<void>{
Return the element instead of void

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        return this.getHeader().locator('span.navbar-brand').innerText();
Add unique locator in a separate get method, and use this method to only return text content

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        let dictionary: ImageDetails = {
No need to add an additional variable here, you can return the object directly, like return {width: details.width,}

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        let details  = await this.getUserIcon().boundingBox({timeout: 2000});
When the variable does not change its value inside a method, initialise it with a const instead of let.

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +     *
Add comment to describe what the method is doing

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
>          expect(
Use await landingPage.getHeaderTextContent() directly as expect param instead of initialising a new variable

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +            ret.height,
Same as above for the expect parameter

2022-04-15 13:34 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +            ret.width,
Same as above for the expect parameter

2022-04-16 09:53 UTC, andreiooo commented on automation/tests/homepage.spec.ts
> +            ret.width,
something like this?
![image](https://user-images.githubusercontent.com/102733517/163670519-5e65e435-20f2-45b3-b5fb-642d3c26abce.png)

2022-04-16 09:53 UTC, andreiooo commented on automation/tests/homepage.spec.ts
>          expect(
solved

2022-04-16 09:54 UTC, andreiooo commented on automation/pages/landingPage.ts
> +     *
Added description above return

2022-04-16 09:55 UTC, andreiooo commented on automation/pages/landingPage.ts
> +        let dictionary: ImageDetails = {
Added for debug purposes, forgot to delete it
solved

2022-04-16 09:55 UTC, andreiooo commented on automation/pages/landingPage.ts
> +        let details  = await this.getUserIcon().boundingBox({timeout: 2000});
changed to const

2022-04-16 09:55 UTC, andreiooo commented on automation/tests/homepage.spec.ts
> +            ret.height,
commented below

2022-04-18 06:15 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +            ret.width,
Yes, can use this structure

2022-04-18 06:17 UTC, Lazar-Adrian requested changes

2022-04-18 06:17 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        return this.getHeader().locator('.user-icon');
Remove nesting from locator find, try to stick with finding each element using a unique selector

2022-04-18 06:17 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
>          await this.getHeader().waitFor({timeout: 3000, state:'attached'});
Return the locator of the element for which the method waits for

2022-04-19 11:02 UTC, andreiooo commented on automation/pages/landingPage.ts
> +    async waitForUserIcon(): Promise<void>{
![image](https://user-images.githubusercontent.com/102733517/163989620-e40d5c6a-d05b-4f09-86b1-fc4c2461de2b.png)
I dont understand what to return, maybe you can be more specific? I did the same as the header

2022-04-19 11:11 UTC, andreiooo commented on automation/pages/landingPage.ts
>          await this.getHeader().waitFor({timeout: 3000, state:'attached'});
Changed to:
![image](https://user-images.githubusercontent.com/102733517/163991260-11fbc427-0232-440f-bf73-8f02ff41cc69.png)


Also,

2022-04-19 13:33 UTC, Lazar-Adrian requested changes

2022-04-19 13:33 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    async getUserIconDetails(): Promise<any> {
Add type instead of any for return object

2022-04-26 14:00 UTC, closed without merging