Intern 21
AndreiToader1/connatix-internship pull request #6
Opened 2022-04-13 13:31 UTC by ralucaaianos

2022-04-18 12:11 UTC, Annno commented on frontend/src/Components/popup/Popup.scss
> +    position: relative;
It's a little bit weird how you are positioning this. You can use text-align: right and margin-right: 12px or something. Also add a cursor pointer on the svg, as it's clickable.

2022-04-18 12:12 UTC, Annno commented on frontend/src/Components/popup/Popup.ts
> +        });
Try to format this part of the code, as it's hard to read the closing parenthesis

2022-04-19 11:55 UTC, ralucaaianos commented on frontend/src/Components/popup/Popup.scss
> +    position: relative;
solved

2022-04-19 11:55 UTC, ralucaaianos commented on frontend/src/Components/popup/Popup.ts
> +        });
solved

2022-04-20 09:24 UTC, Annno approved these changes

2022-04-26 10:53 UTC, Lazar-Adrian requested changes

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    userPopup: any;
No need for this to be declared here

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    getPopupTitleText: any;
Same as above

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    getPopUp(): Locator{
Check indentation of added methods

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +   async waitForTitle(): Promise<any>{
Add descriptive comment for added methods

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +   async waitForTitle(): Promise<any>{
It should return Locator instead of any

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +    // test('The "User Icon" should be loaded and visible', async ({page}) => {
Remove commented code

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +        await page.click('#button');
The page element on which the click() action is called, should come from a page object class instead of defining the locator inside the test

2022-04-26 10:53 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +        await page.click('#button');
Same as above

2022-04-26 13:57 UTC, merged