Add "Create user" button
AndreiToader1/connatix-internship pull request #8
Opened 2022-04-14 11:23 UTC by Silvian-Alb

2022-04-18 07:14 UTC, Annno approved these changes

2022-04-20 17:04 UTC, Lazar-Adrian requested changes

2022-04-20 17:04 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +        await this.getAddUserButton().waitFor({timeout: 3000, state:'attached'});
Discuss with Andrei and return Locator instead of void for this method

2022-04-20 17:04 UTC, Lazar-Adrian commented on automation/pages/landingPage.ts
> +    async getButtonText(): Promise<String>{
Update method name to math actual return, i.e. getAddUserButtonText()

2022-04-20 17:04 UTC, Lazar-Adrian commented on automation/tests/homepage.spec.ts
> +    test.only('The "Button" should be loaded', async ({page}) => {
No need for the .only()

2022-04-21 08:48 UTC, bOb-Mihai commented on automation/pages/landingPage.ts
> +        await this.getAddUserButton().waitFor({timeout: 3000, state:'attached'});
Can you explain to me why i have to do this(what is the logit behind this change) and how i can do it ?

2022-04-21 08:51 UTC, bOb-Mihai commented on automation/pages/landingPage.ts
> +    async getButtonText(): Promise<String>{
solved

2022-04-21 08:56 UTC, bOb-Mihai commented on automation/tests/homepage.spec.ts
> +    test.only('The "Button" should be loaded', async ({page}) => {
i know but i did that so i don't have to run Andrei tests because always returns 1 failed test (the webkit one) and i didn't want to combine my failed tests with his failed tests

2022-04-21 12:53 UTC, merged